Fix compilation on gcc >= 14
`./configure` fails for gcc >= 14 with the following error

```
checking "libosip prefix"... 
checking for osip_init in -losip2... yes
checking for parser_init in -losipparser2... yes
checking libosip2 version > 3.0.0... *** ERROR: libosip2-3.x.x is required!
```

which in fact is caused by the test program in `ACX_CHECK_LIBOSIP_VERSION` function in `acinclude.m4` due to

```
conftest.c:4:3: error: return type defaults to ‘int’ [-Wimplicit-int]                                                                                                                                                                                                                       
    4 | main() {                                                                                                                                                                                                                                                                            
      | ^~~~                                                              
```

This patch fixes the issue!